services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse-api_development
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      - redis
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0

  application:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
        NODE_ENV: development
    stdin_open: true
    tty: true
    command: ["./entrypoint.sh", "bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]
    ports:
      - "3000:3000"
      - "3009:3009"
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0

volumes:
  postgres:
  redis:
